import React, { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { deleteData, getData } from "../components/backendUri";

function Home() {
  const router = useRouter();
  const [Quotes, setQuotes] = useState([]);
  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      return router.replace("/");
    }
    getQuoteData();
  }, [router]);

  const LogoutUser = () => {
    localStorage.removeItem("token");
    router.replace("/");
  };
  const CreateQuote = () => {
    router.push("/create");
  };
  const updateQuote = (id) => {
    router.push("/update", {
      query: {
        id,
      },
    });
  };
  const deleteQuote = async (id) => {
    const response = await deleteData(`/crud/delete/${id}`);
    if (response) {
      const filteredQuotes = Quotes.filter(
        (item) => item._id !== response.response._id
      );
      setQuotes(filteredQuotes);
    } else {
      console.log("Error");
    }
  };
  const getQuoteData = async () => {
    const response = await getData("/crud/read");
    setQuotes(response.response);
  };
  return (
    <>
      <Head>
        <title>Frontend Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="FormHere">
        <div>You are accessing protected routes</div>
        <div>
          <button onClick={LogoutUser} className="registerBtn">
            Logout
          </button>
        </div>
        <div>
          <button onClick={CreateQuote} className="registerBtn">
            Create Quote
          </button>
        </div>
      </div>
      <h1 style={{textAlign:"center"}}>Create Quotes and read below</h1>
      <div className="QuoteHere">
        {Quotes.map((e) => (
          <div
            style={{
              display: "flex",
              height: 100,
              width: "50%",
              alignItems: "center",
              justifyContent: "space-evenly",
              border: "3px dashed dodgerblue",
              borderRadius: 20,
              marginBottom: 10,
            }}
            key={e._id}
          >
            <div>
              <div>Quote = {e.title}</div>
              <div>By = {e.description}</div>
            </div>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                height: "100%",
                alignItems: "center",
                justifyContent: "space-evenly",
              }}
            >
              <div
                style={{
                  cursor: "pointer",
                  color: "red",
                }}
                onClick={() => deleteQuote(e._id)}
              >
                Delete
              </div>
              <div
                style={{
                  cursor: "pointer",
                  color: "orange",
                }}
                onClick={() => updateQuote(e._id)}
              >
                Update
              </div>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}

export default Home;
