import Head from "next/head";
import Navbar from "./components/Navbar";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { postData } from "./components/backendUri";
export default function Home() {
  const router = useRouter();
  useEffect(() => {
    const getValues = async () => {
      const token = localStorage.getItem("token");
      if (token) {
        return router.push("/home");
      }
    };
    getValues();
  }, [router]);
  const [FormData, setFormData] = useState({
    email: "",
    password: "",
  });
  const OnChangeHandler = (name, value) => {
    setFormData({ ...FormData, [name]: value });
  };

  const LoginUser = async () => {
    const response = await postData("/login", FormData);
    if (response) {
      setFormData({
        email: "",
        password: "",
      });
      router.replace("/home");
    } else {
      console.log("Error");
    }
  };
  return (
    <>
      <Head>
        <title>Frontend Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar pass="Login" />
      <div className="FormHere">
        <div>
          <label>Email</label>
          <br />
          <input
            onChange={(e) => OnChangeHandler("email", e.target.value)}
            type={"email"}
            spellCheck={false}
            autoCorrect="false"
            value={FormData.email}
          />
        </div>
        <div>
          <label>Password</label>
          <br />
          <br />
          <input
            type={"password"}
            spellCheck={false}
            autoCorrect="false"
            onChange={(e) => OnChangeHandler("password", e.target.value)}
            value={FormData.password}
          />
        </div>
        <div>
          <button onClick={LoginUser} className="registerBtn">
            Login
          </button>
        </div>
      </div>
    </>
  );
}
