import React, { useEffect, useState } from "react";
import Navbar from "./components/Navbar";
import Head from "next/head";
import { useRouter } from "next/router";
import { postData } from "./components/backendUri";

function register() {
  const router = useRouter();
  const [FormData, setFormData] = useState({
    username: "",
    email: "",
    password: "",
  });
  useEffect(() => {
    const getValues = async () => {
      const token = localStorage.getItem("token");
      if (token) {
        router.push("/home");
      }
    };
    getValues();
  }, []);
  const OnChangeHandler = (name, value) => {
    setFormData({ ...FormData, [name]: value });
  };

  const RegisterUser = async () => {
    const response = await postData("/register", FormData);
    setFormData({
      username: "",
      email: "",
      password: "",
    });
    if (response) {
      router.replace("/home");
    } else {
      console.log("Error");
    }
  };
  return (
    <>
      <Head>
        <title>Frontend Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar pass="Register" />
      <div className="FormHere">
        <div>
          <label>Username</label>
          <br />
          <input
            onChange={(e) => OnChangeHandler("username", e.target.value)}
            type={"text"}
            spellCheck={false}
            autoCorrect="false"
            value={FormData.username}
          />
        </div>
        <div>
          <label>Email</label>
          <br />
          <input
            type={"email"}
            spellCheck={false}
            autoCorrect="false"
            onChange={(e) => OnChangeHandler("email", e.target.value)}
            value={FormData.email}
          />
        </div>
        <div>
          <label>Password</label>
          <br />
          <input
            type={"password"}
            spellCheck={false}
            autoCorrect="false"
            onChange={(e) => OnChangeHandler("password", e.target.value)}
            value={FormData.password}
          />
        </div>
        <div>
          <button onClick={RegisterUser} className="registerBtn">
            Register
          </button>
        </div>
      </div>
    </>
  );
}

export default register;
